# Generated by Django 5.0.1 on 2024-02-14 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapp',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listapp',
            name='mark_as_completed',
            field=models.BooleanField(default=False),
        ),
    ]
