# Generated by Django 5.0.2 on 2024-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listapp_date_created_listapp_mark_as_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapp',
            name='mark_as_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
