# Generated by Django 5.0.2 on 2024-03-03 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_full_name_user_address_user_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefdefinelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('image_a', models.ImageField(default=None, upload_to='listimage')),
                ('image_b', models.ImageField(default=None, upload_to='listimage')),
                ('mark_as_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
