# Generated by Django 5.0.2 on 2024-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prefdefinelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapp',
            name='image_a',
            field=models.ImageField(default=None, null=True, upload_to='listimage'),
        ),
        migrations.AlterField(
            model_name='listapp',
            name='image_b',
            field=models.ImageField(default=None, null=True, upload_to='listimage'),
        ),
        migrations.AlterField(
            model_name='prefdefinelist',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='prefdefinelist',
            name='image_a',
            field=models.ImageField(default=None, null=True, upload_to='listimage'),
        ),
        migrations.AlterField(
            model_name='prefdefinelist',
            name='image_b',
            field=models.ImageField(default=None, null=True, upload_to='listimage'),
        ),
    ]
