# Generated by Django 5.0.2 on 2024-03-03 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_listapp_image_a_alter_listapp_image_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('image_a', models.ImageField(default=None, null=True, upload_to='social/post')),
                ('image_b', models.ImageField(default=None, null=True, upload_to='social/post')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
