# Generated by Django 5.0.2 on 2024-03-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_socialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
